### PR TITLE
Revert "Do not expose control sizes and positions on Transifex"

### PR DESCRIPTION
**Pull request by nguyenq**
Reverts nguyenq/VietOCR3.NET#3

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
Please revert this revert.

The problem is that due to whatever reasons, these numbers still get out of sync between git and Transifex, which means that when I prepare my PR, I have to cherry-pick the changes line-by-line anyway. I'd rather avoid removing the numbers maintained by you than show them as available for localization just to avoid changing them later.

If we could have all these positioning strings somewhere at the bottom of the file, that would be even more awesome, but even if not, this just doesn't work the way we have it now, so there's no point in cluttering Transifex with these "translatables".

**Comment by rimas-kudelis** [comment]
I mean, here's how my diff currently looks after a fresh pull from Transifex.
Whether or not I tell localizers not to touch these strings is irrelevant, because if you touch them outside of Transifex, they get out of sync anyway, which defeats the whole point of exposing them to the localizers in the first place.

gitg

**Comment by nguyenq** [comment]
The second values look like coming from the base GUI.resx. Once taken from
the base to establish a new localized resource, the Transifex tool should
not touch those values any more, unless they are new strings to be
localized.

Otherwise, when merging the pull request, the localized position/size
currently in Git repository would get removed by the updated files from
Transifex, if the Transifex files do not contain them.

If things worked as it is supposed to, neither of us would need to cherry
pick anything; it should accept the whole updated file as is. When in the
process is thing broken? When Transifex is synchronized with Git, the files should be identical, right? As the release is imminent, the localization is frozen, please sync Transifex with Git.

As to the reordering of the items in the resource files, it would be impractical because it is controlled by Visual Studio. Whatever manual changes were made will be overwritten by VS IDE.

**Comment by rimas-kudelis** [comment]
If things worked as they were supposed to, we wouldn't be discussing this because either they would just work, or they would just work the other way, but still would work.

The thing is: I don't do pushes of localized resources from git to Transifex. Transifex only pulls the (transformed) English files, and I pull the localized files from it. This allows me not to worry about unwillingly overwriting newer translations with older ones or untranslated English strings.
But this also means that the updates you perform on localized files are never propagated to Transifex.

For example, when you change some Location string in the English file, Transifex sees that as a change, and presents it to the localizers for "translation".

Another example: if you change a Location string in the localized file, that change is not propagated to Transifex, and Transifex gets out of sync with git. It "thinks" that the translation to string "A" is "B", while you've in fact changed it to "C" already.

One way to fix this would be to pull the translation files right before adjusting these positions and sizes, and then right after that to push these translated files back, but I don't think it's worth the trouble, since it might have other adverse effects such as treating an untranslated English string as translated.

**Comment by nguyenq** [comment]
I have always been under the impression that you had, upon request,
periodically performed the sync of localized files from VietOCR project to
Transifex using some type of facility provided by Transifex. That seemed to
be the process that had been in use in the past until now, when you brought
up to light the issue of having size/location values in the localized
files. We have several hundreds of those values in each set of language
files; multiply that with the number of the supported languages and we have
them in the thousands. They'd be best to be managed automatically, or it
would be a hugely time-consuming task neither of us can spend effort to
maintain. I still wonder how it worked in the past.

Now based on the given information that only the English base
resources/properties files are synced up, albeit one-day lag in the time
when there are changes, we need to come up with a way that would not burden
both sides. Git repo has, and must have, all the current values. It's
logical that Transifex should have the same values, when possible, by some
sync process.

If Transifex does not provide that support and if the localized files now
would no longer have the size/location values, I would not accept any pull
request from you since it would remove any existing size/location data. I'm
not familiar with Transifex handling of the translation files, so can't
offer any idea to help. But what can be done?

**Comment by rimas-kudelis** [comment]
Like I said, my PR's would NOT remove any existing size/location values, because I would take care of that, same way as I do now, but hopefully faster. And even if not faster, at least we would avoid showing these strings to localizers who aren't supposed to touch them anyway.

A localization tool which would work directly with a git repo and catch all external updates from there would be nice, but Transifex is no such tool. I chose Transifex because it had an agreeable UI and was one of the very few tools to support both .properties and .resx file formats at the time.

Doing manual mergers is a huge annoyance, but I don't know how to avoid it with you silently updating localized files on your side and not pushing these updates to Transifex yourself. I mean, ideally, if you wanted to change something (e.g. a mnemonic key in a .properties file, or a size constraint in .resx), you would pull the affected file from Tx, make your change, and push that file back to Tx right away. This way possible loss of work would be minimal, and things would be kept in sync. But this is not the way we're doing business at the moment.

This problem with size/location strings could also be solved by migrating away from ugly WinForms to WPF, but I don't suppose you have time for that.

**Pull request merged**
